apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "portscan-prometheus-exporter.serviceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "portscan-prometheus-exporter.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "portscan-prometheus-exporter.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "portscan-prometheus-exporter.serviceAccountName" . }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]