apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "portscan-prometheus-exporter.fullname" . }}
  labels:
    {{- include "portscan-prometheus-exporter.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "portscan-prometheus-exporter.labels" . | nindent 6 }}
  endpoints:
  - port: metrics